### ISSUE TITLE
Watchlist not starting or re-starting server (polka in this instance)

### ISSUE THREAD

**Issue by newtriks** [lukeed/watchlist#12]
## Steps:

1. Setup a simple project using Polka for example: https://www.npmjs.com/package/polka#usage
2. Add a `"start"` script e.g. `"start": "node src/index.js"`
3. Add a script to watch and re-run `"start"` e.g. `"dev": "watchlist src -- npm start"`

## Expected

Server restarts on file changes in `src`

## Actual

1. `"dev"` script does not actually start the server
2. Watchlist clears console on change but still the server is not run

**Comment by lukeed** [comment]
Hey,

So this is the same issue as #11 actually. The server doesn't start immediately. With the current `watchlist`, you have to make a change in any of your `src/*` files. This will trigger the command for the first time, starting your server.

**Comment by newtriks** [comment]
👋  @lukeed thanks for the reply. I've attached a screen recording of what's happening to me and a zip of the example project. To clarify my steps:

1. `npm run dev`
2. Save file
3. `curl http://localhost:3000/users/polka`
4. Change response from `User` to log `Users`
5. Save file
6. `curl http://localhost:3000/users/polka`

- After step 2 and step 5 (saving file) it clears the terminal window but doesn't show the console log `> Running on localhost:3000`.
- After step 6 it still returns `User` and not `Users` in the response i.e. the server isn't reflecting the latest changes.

https://user-images.githubusercontent.com/31971/118470789-eda69d80-b6fe-11eb-836d-1e294c478e98.mov

[polkadot.zip](https://github.com/lukeed/watchlist/files/6493020/polkadot.zip)

**Comment by ArtskydJ** [comment]
@newtriks There are multiple things going on:

First, `watchlist` buffers the console output until the command exits.  That's why you don't see `> Running on localhost:3000`

`watchlist` doesn't run the command if it's already in-progress.  Since your server doesn't shut down, it's always considered to be "in-progress".  Thus, `watchlist` is ignoring all changes after your first change.

Maybe you want to try [`nodemon`](https://www.npmjs.com/package/nodemon) or similar.  `nodemon` was designed to restart hanging processes.

**Comment by newtriks** [comment]
@ArtskydJ makes sense, thank you 🙏
